services:
  odoo:
    build: 
      context: .
      args:
        GIT_TOKEN: ${GIT_TOKEN}
        GIT_ENTERPRISE_TOKEN: ${GIT_ENTERPRISE_TOKEN}
        GIT_REPOSITORY: ${GIT_REPOSITORY}
        GIT_BRANCH: ${GIT_BRANCH}
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        MASTER_PASSWORD: ${MASTER_PASSWORD}
        LIST_DB: ${LIST_DB}
        DB_FILTER: ${DB_FILTER}
    container_name: odoo19
    depends_on: []
    ports:
      - "8069:8069"
      - "8071:8071"
      - "8072:8072"
    volumes:
      - odoo-data:/var/lib/odoo
      - /root/odoo/assets:/var/lib/odoo/.local/share/Odoo/
      - /root/odoo/backups:/mnt/backups
      - .env:/.env
    environment:
      - HOST=host.docker.internal
      - PORT=5432
      - USER=admin
      - PASSWORD=admin
      - DATABASE=odoo19
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    command: odoo --config=/etc/odoo/odoo.conf
    labels:
      - traefik.enable=true

      # Router normal -> puerto 8069 (HTTP)
      - traefik.http.routers.odoo-http.rule=Host(`evolvestage.ebc-cloud.com`)
      - traefik.http.routers.odoo-http.entrypoints=https
      - traefik.http.routers.odoo-http.tls=true
      - traefik.http.routers.odoo-http.tls.certresolver=letsencrypt
      - traefik.http.routers.odoo-http.service=odoo-http
      - traefik.http.services.odoo-http.loadbalancer.server.port=8069

      # Router websocket -> puerto 8072 (mayor prioridad, debe matchear primero)
      - traefik.http.routers.odoo-ws.rule=Host(`evolvestage.ebc-cloud.com`) && PathPrefix(`/websocket`)
      - traefik.http.routers.odoo-ws.entrypoints=https
      - traefik.http.routers.odoo-ws.tls=true
      - traefik.http.routers.odoo-ws.tls.certresolver=letsencrypt
      - traefik.http.routers.odoo-ws.priority=10
      - traefik.http.routers.odoo-ws.service=odoo-ws
      - traefik.http.services.odoo-ws.loadbalancer.server.port=8072
      - traefik.http.routers.odoo-ws.priority=1000

volumes:
  odoo-data:
    driver: local

